"""JS<->Python parity for site/verify.js (offline).

tests/fixtures/verify_parity.json holds input tuples plus expected outputs.
This test recomputes every expectation with formulas.py / score.py, so the
fixture can never drift from the Python source of truth. The same fixture is
asserted against site/verify.js under Node by scripts/check_verify_parity.mjs
(tolerance 1e-6; 1e-5 for delta, covering its erf approximation).

Regenerate after changing the formulas or the case list:

    python tests/test_verify_parity.py
"""
import json
import math
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import formulas
import score as score_mod

FIXTURE = Path(__file__).parent / "fixtures" / "verify_parity.json"

# (name, bid, ask, spot, strike, dte, iv) — r=0.04, floor=0.01 throughout.
CASES = [
    ("typical_35dte", 2.70, 2.90, 140.0, 130.0, 35, 0.28),
    ("tight_spread_low_iv", 0.55, 0.60, 62.0, 58.0, 40, 0.16),
    ("wide_spread", 1.00, 1.60, 100.0, 92.0, 30, 0.35),
    ("high_iv", 6.10, 6.50, 90.0, 75.0, 45, 2.00),
    ("very_low_iv", 0.10, 0.14, 50.0, 47.0, 35, 0.05),
    ("one_day_left", 0.20, 0.30, 100.0, 97.0, 1, 0.40),
    ("strike_near_spot", 4.20, 4.40, 100.0, 99.5, 35, 0.25),
    ("strike_above_spot", 8.00, 8.40, 100.0, 105.0, 35, 0.30),
    ("zero_bid", 0.00, 0.20, 80.0, 70.0, 42, 0.30),
    ("deep_otm", 0.06, 0.10, 250.0, 180.0, 31, 0.45),
    ("expensive_stock", 11.5, 12.1, 820.0, 760.0, 38, 0.22),
    ("long_stretch_dte", 3.10, 3.30, 150.0, 138.0, 56, 0.24),
]

R = 0.04
FLOOR = 0.01


def _expected(bid, ask, spot, strike, dte, iv):
    m = formulas.mid(bid, ask)
    # main._effective_premium, conservative basis, for a live typed quote.
    premium = (bid + m) / 2.0 if bid > 0 else m
    delta = formulas._bs_put_delta_native(spot, strike, dte, iv, R)
    row = {
        "strike": strike, "dte": dte, "iv": iv,
        "annualized_yield": formulas.annualized_yield(premium, strike, dte),
        "abs_delta": abs(delta),
    }
    config = {"quality": {"score_denominator_floor": FLOOR},
              "scoring": {"mode": "risk_adjusted"}}
    scored = score_mod.score_candidate(row, config, spot)
    return {
        "mid": m,
        "spread_pct": formulas.spread_pct(bid, ask),
        "premium_conservative": premium,
        "yield_30dte_mid": formulas.yield_30dte(m, strike, dte),
        "annualized_yield": row["annualized_yield"],
        "implied_move": formulas.implied_move(iv, dte),
        "distance_to_strike": formulas.distance_to_strike(spot, strike),
        "put_delta": delta,
        "score_risk_adjusted": scored["score"],
    }


def _build():
    cases = []
    for name, bid, ask, spot, strike, dte, iv in CASES:
        cases.append({
            "name": name,
            "inputs": {"bid": bid, "ask": ask, "spot": spot, "strike": strike,
                       "dte": dte, "iv": iv, "r": R, "floor": FLOOR},
            "expected": _expected(bid, ask, spot, strike, dte, iv),
        })
    return {"note": "Generated by tests/test_verify_parity.py — do not edit by hand.",
            "cases": cases}


def test_fixture_matches_python():
    doc = json.loads(FIXTURE.read_text())
    assert len(doc["cases"]) == len(CASES)
    for case, (name, bid, ask, spot, strike, dte, iv) in zip(doc["cases"], CASES):
        assert case["name"] == name
        expected = _expected(bid, ask, spot, strike, dte, iv)
        for key, val in expected.items():
            assert case["expected"][key] == pytest.approx(val, rel=1e-12, abs=1e-12), \
                f"{name}.{key} drifted from Python — regenerate the fixture"


def test_fixture_values_are_finite():
    doc = json.loads(FIXTURE.read_text())
    for case in doc["cases"]:
        for key, val in case["expected"].items():
            assert isinstance(val, (int, float)) and math.isfinite(val), \
                f"{case['name']}.{key} is not a finite number"


if __name__ == "__main__":
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(_build(), indent=2) + "\n")
    print(f"wrote {FIXTURE}")
